---
version: 2

project_name: endoflife_exporter

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: endoflife_exporter
    main: .
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"
