// Package endoflife provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package endoflife

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// FullProductListResponse A response containing a list of products (full).
type FullProductListResponse struct {
	// GeneratedAt The time this response was generated.
	GeneratedAt time.Time `json:"generated_at"`

	// Result The products.
	Result []ProductDetails `json:"result"`

	// SchemaVersion Version of this schema.
	SchemaVersion string `json:"schema_version"`

	// Total Number of products in the list.
	Total int32 `json:"total"`
}

// Identifier A product identifier, such as a purl, repology or cpe identifier.
type Identifier struct {
	// Id Identifier.
	Id string `json:"id"`

	// Type Type of the identifier.
	Type string `json:"type"`
}

// IdentifierListResponse A response containing all identifiers for a given type.
type IdentifierListResponse struct {
	// GeneratedAt The time this response was generated.
	GeneratedAt time.Time `json:"generated_at"`

	// Result The identifiers.
	Result []struct {
		// Identifier The identifier.
		Identifier string `json:"identifier"`

		// Product Reference to the product this identifier is related to.
		Product Uri `json:"product"`
	} `json:"result"`

	// SchemaVersion Version of this schema.
	SchemaVersion string `json:"schema_version"`

	// Total Number of identifiers in the list.
	Total int32 `json:"total"`
}

// ProductDetails Full details of a product.
type ProductDetails struct {
	// Aliases Aliases declared for the product (derived from alternate_urls).
	// The array is empty when no alias is declared.
	Aliases []string `json:"aliases"`

	// Category Category of the product.
	Category string `json:"category"`

	// Identifiers Known identifiers (purl, repology, cpe...) associated to the product.
	// The array is empty when no identifier is declared.
	Identifiers []Identifier `json:"identifiers"`

	// Label Label of the product.
	Label string `json:"label"`

	// Labels Product labels.
	Labels struct {
		// Discontinued Label used to denote the discontinuation of the product.
		// This field is mainly used for hardware, it is always null for software.
		Discontinued *string `json:"discontinued"`

		// Eoas Label used to denote the phase before the end of active support of the product.
		// This field is null when the product does not have an active support phase.
		Eoas *string `json:"eoas"`

		// Eoes Label used to denote the phase before the end of extended support of the product.
		// This field is null when the product does not have an extended support phase.
		Eoes *string `json:"eoes"`

		// Eol Label used to denote the phase before the end of life of the product.
		Eol string `json:"eol"`
	} `json:"labels"`

	// Links Product links.
	Links struct {
		// Html Link to the product page on endoflife.date.
		Html string `json:"html"`

		// Icon Link to the product icon on https://simpleicons.org.
		// This field is null when the product does not have an icon on simpleicons.org.
		Icon *string `json:"icon"`

		// ReleasePolicy Link to the product release policy.
		// This field is null when the product does not have a publicly available release policy.
		ReleasePolicy *string `json:"releasePolicy"`
	} `json:"links"`

	// Name Name of the product.
	Name string `json:"name"`

	// Releases A list of all product releases.
	Releases []ProductRelease `json:"releases"`

	// Tags Tags associated to the product.
	// Given the category is also a tag, the array will always contain at least one tag.
	Tags []string `json:"tags"`

	// VersionCommand Command that can be used to check the current product version.
	// This field is null when the command is not known.
	VersionCommand *string `json:"versionCommand"`
}

// ProductListResponse A response containing a list of products (summary).
type ProductListResponse struct {
	// GeneratedAt The time this response was generated.
	GeneratedAt time.Time `json:"generated_at"`

	// Result The products.
	Result []ProductSummary `json:"result"`

	// SchemaVersion Version of this schema.
	SchemaVersion string `json:"schema_version"`

	// Total Number of products in the list.
	Total int32 `json:"total"`
}

// ProductRelease Full information about a product release cycle.
type ProductRelease struct {
	// Codename Codename of the product release cycle.
	// This field is null when the release cycle does not have a codename, or when the information is not known.
	Codename *string `json:"codename"`

	// Custom Custom fields for the product release cycle.
	// This field is null when the product does not declare at least one custom fields.
	Custom *UnknownProperties `json:"custom"`

	// DiscontinuedFrom Discontinuation date for the release cycle.
	// This field is mainly used for hardware, it is not provided when not applicable. It is null when the date is not known.
	DiscontinuedFrom *openapi_types.Date `json:"discontinuedFrom"`

	// EoasFrom End of active support date for the release cycle.
	// This field is not provided when the product does not have an active support phase. It is null when the date is not known.
	EoasFrom *openapi_types.Date `json:"eoasFrom"`

	// EoesFrom End of extended support date for the release cycle.
	// This field is not provided when the product does not have an extended support phase. It is null when the release cycle is not eligible for extended support or when the date is not known.
	EoesFrom *openapi_types.Date `json:"eoesFrom"`

	// EolFrom End of life date for the release cycle.
	// This field is null when the date is not known.
	EolFrom *openapi_types.Date `json:"eolFrom"`

	// IsDiscontinued Whether the release cycle is discontinued.
	// This field is mainly used for hardware, it is not provided when not applicable.
	IsDiscontinued *bool `json:"isDiscontinued,omitempty"`

	// IsEoas Whether the active support phase is over for the release cycle.
	// This field is not provided when the product does not have an active support phase.
	IsEoas *bool `json:"isEoas,omitempty"`

	// IsEoes Whether the extended support phase is over for the release cycle.
	// This field is not provided when the product does not have an extended support phase. This field is null when the release cycle is not eligible for extended support.
	IsEoes *bool `json:"isEoes"`

	// IsEol Whether the release cycle is EOL.
	IsEol bool `json:"isEol"`

	// IsLts Whether the product release cycle receives long-term support (LTS).
	IsLts bool `json:"isLts"`

	// IsMaintained Whether this release cycle still have some level of support.
	// This can be any level of support, even extended support.
	IsMaintained bool `json:"isMaintained"`

	// Label Label of the product release cycle.
	Label string `json:"label"`

	// Latest Latest version for this release cycle.
	// This field is null when this release cycle does not have a latest version documented.
	Latest *ProductVersion `json:"latest"`

	// LtsFrom Start date of the LTS phase for the release cycle.
	// This field is null when the isLts field is set to false, when the LTS phase does not start later than the release date, or when the date is not known.
	LtsFrom *openapi_types.Date `json:"ltsFrom"`

	// Name Name of the product release cycle.
	Name string `json:"name"`

	// ReleaseDate Release date of the release cycle.
	ReleaseDate openapi_types.Date `json:"releaseDate"`
}

// ProductReleaseResponse A response containing a release cycle.
type ProductReleaseResponse struct {
	// GeneratedAt The time this response was generated.
	GeneratedAt time.Time `json:"generated_at"`

	// Result Full information about a product release cycle.
	Result ProductRelease `json:"result"`

	// SchemaVersion Version of this schema.
	SchemaVersion string `json:"schema_version"`
}

// ProductResponse A response containing a product.
type ProductResponse struct {
	// GeneratedAt The time this response was generated.
	GeneratedAt time.Time `json:"generated_at"`

	// LastModified The time this product was last modified.
	LastModified time.Time `json:"last_modified"`

	// Result Full details of a product.
	Result ProductDetails `json:"result"`

	// SchemaVersion Version of this schema.
	SchemaVersion string `json:"schema_version"`
}

// ProductSummary Summary of a product.
type ProductSummary struct {
	// Aliases Aliases declared for the product (derived from alternate_urls).
	// The array is empty when no alias is declared.
	Aliases []string `json:"aliases"`

	// Category Category of the product.
	Category string `json:"category"`

	// Label Label of the product.
	Label string `json:"label"`

	// Name Name of the product.
	Name string `json:"name"`

	// Tags Tags associated to the product.
	// Given the category is also a tag, the array will always contain at least one tag.
	Tags []string `json:"tags"`

	// Uri Link to the full product details.
	Uri string `json:"uri"`
}

// ProductVersion Information about a product version.
type ProductVersion struct {
	// Date Release date of the version.
	// This field is null when the information is not known.
	Date *openapi_types.Date `json:"date"`

	// Link Link to the changelog or release notes.
	// This field is null when there is no public link available, or when the information is not known.
	Link *string `json:"link"`

	// Name Name of the version.
	Name string `json:"name"`
}

// UnknownProperties Group properties with name not know in advance, such as custom properties.
type UnknownProperties map[string]*string

// Uri A link to a resource.
type Uri struct {
	// Name Name of the URI.
	Name string `json:"name"`

	// Uri URI.
	Uri string `json:"uri"`
}

// UriListResponse A response containing a list of URIs.
type UriListResponse struct {
	// GeneratedAt The time this response was generated.
	GeneratedAt time.Time `json:"generated_at"`

	// Result The URIs.
	Result []Uri `json:"result"`

	// SchemaVersion Version of this schema.
	SchemaVersion string `json:"schema_version"`

	// Total Number of URIs in the list.
	Total int32 `json:"total"`
}
