{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "product",
    "label": "Product Name",
    "query": {
     "query": "label_values(endoflife_product_info,product_name)"
    }
   },
   {
    "name": "release_cycle",
    "label": "Release Cycle",
    "query": {
     "query": "label_values(endoflife_product_info{product_name=\"$product\"},release_cycle_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Products Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(endoflife_product_info{product_name=\"$product\",release_cycle_name=\"$release_cycle\"}) by (is_maintained,is_eol,is_eol)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EOL Data",
   "type": "stat",
   "description": "End of life date",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endoflife_eol_from_timestamp_seconds{product_name=\"$product\", release_cycle_name=\"$release_cycle\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Release Date",
   "type": "stat",
   "description": "Product release date",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endoflife_release_cycle_timestamp_seconds{product_name=\"$product\", release_cycle_name=\"$release_cycle\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}